config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  resources :clients
  root to: "clients#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_manager!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  skip_before_action :authenticate_manager!, only: :home
  before_action :set_client, only: %i[ show edit update destroy ]

  def home
  end

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :account, :password, :email, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= client.account %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= client.password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= client.message %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :account %>
    <%= f.input :password %>
    <%= f.input :email %>
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/home.html.erb
<h1>Home page</h1>
<%= link_to 'View Clients', clients_path, class:'btn btn-success'  %>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerencial</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Gerencial", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if manager_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag 'perfil', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_manager_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_manager_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>